stages:
  process:
    cmd: python process_data.py
    deps:
    - base_english.csv
    - process_data.py
    outs:
    - data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - learning_info.png
    - confusion_matrix.png
    metrics:
    - metrics.json:
        cache: false
    metrics:
    - hyperparam.json:
        cache: false