name: dvc-cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.14
      - namd: Install tensorflow
        run: |
          pip install tensorflow==2.5.0
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch --prune ## https://git-scm.com/docs/git-fetch
          dvc metrics diff --show-md master > report.md

          echo "## Validating results by region"
          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md